name: orientation_picker
description: A simple convenience widget for Flutter to conditionally display (or hide) other widgets based on device orientation (or aspect ratio).
version: 0.0.1-alpha.1
homepage: https://github.com/matt-addams/orientation_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
